### PR TITLE
Fix use generic identifier

### LINKED ISSUE #64: Start using a Generic identifier for the restaurants
We've had several issues using the name as id for the restaurants. Due to that, it's a better approach to use a generic ID for that, by using a hash based in a sha1 or uuid's.

### PR DESCRIPTION
**Pull request by albertinisg**
This PR fixes #64 

Note that this change must be done on top of #68

### CODE REVIEW

File: server/utils.js [hunk 1]
```diff
@@ -752,14 +774,26 @@ function getTimeBetweenDates(from, to) {
...
       'value': occupancyLevel
     }
   };
 }
 
+function generateId(name, date) {
+  if (date) {
+  return crypto.createHash('sha1').update(name + date).digest('hex');
+  } else {
+  return crypto.createHash('sha1').update(name).digest('hex');
```
Comment (jmcanterafonseca) [inline server/utils.js]: nit: check indentation

File: server/utils.js [hunk 2]
```diff
@@ -632,36 +636,51 @@ function getOrgReservations(franchise, listOfRestaurants, listOfReservations) {
...
-  );
+  if (queryString) {
+    return authRequest(
+      uri,
+      method,
+      body,
+      headers
+    );
+  } else {
+    return authRequest(
```
Comment (jmcanterafonseca) [inline server/utils.js]: instead of doing this, apply this logic to the authRequest method to make queryString an optional parameter at that level and avoid this check that would have to be repeated everytime you use the same code pattern

File: server/utils.js [hunk 3]
```diff
@@ -632,36 +636,51 @@ function getOrgReservations(franchise, listOfRestaurants, listOfReservations) {
...
 
-function getListByType(type, element, headers) {
+function getListByType(type, element, headers, normalized) {
   var uri = '/v2/entities';
+  var options = {'type': type,'limit': '1000'};
   if (element) {
     uri += '/' + encodeURIComponent(element);
   }
+
+  if (typeof normalized === 'undefined') {
```
Comment (jmcanterafonseca) [inline server/utils.js]: nit: if (!normalized)

File: server/utils.js [hunk 4]
```diff
@@ -632,36 +636,51 @@ function getOrgReservations(franchise, listOfRestaurants, listOfReservations) {
...
+        return restaurant.name === element.reservationFor;
       });
     }
   );
 }
 
-function getListByType(type, element, headers) {
+function getListByType(type, element, headers, normalized) {
   var uri = '/v2/entities';
+  var options = {'type': type,'limit': '1000'};
```
Comment (jmcanterafonseca) [inline server/utils.js]: shouldn't 1000 be a constant and a number?

File: server/utils.js [hunk 5]
```diff
@@ -464,44 +465,47 @@ function dataToSchema(listOfElements) {
...
   if (geoObject) {
-    schemaObject.position = {};
-    schemaObject.position.type = 'coords';
-    schemaObject.position.location = 'WGS84';
-    schemaObject.position.value = geoObject.latitude + ', ' +
-      geoObject.longitude;
+    schemaObject.location = {
+      'type': 'geo:point',
+      'value': geoObject.latitude + ', ' +
+        geoObject.longitude
```
Comment (jmcanterafonseca) [inline server/utils.js]: I think they can go in the same line

File: server/utils.js [hunk 6]
```diff
@@ -464,44 +465,47 @@ function dataToSchema(listOfElements) {
 }
 
 function fixAddress(schemaObject, geoObject) {
+  // The returned object will be POST/PATCH(ed),
```
Comment (jmcanterafonseca) [inline server/utils.js]: various comments here:

the name of the function seems to be misleading fix??
on the other hand you can use options=keyValues in updates as well

File: server/utils.js [hunk 7]
```diff
@@ -577,7 +581,7 @@ function getOrgRestaurants(org, listOfElements) {
 function getUserReviews(user, listOfElements) {
   return objectToArray(listOfElements).filter(
     function(element) {
-      return element.author.name === user;
+      return element.author === user;
```
Comment (jmcanterafonseca) [inline server/utils.js:590]: Couldn't these filters being implemented by means of NGSI v2 queries?

**Comment by jmcanterafonseca** [comment]
overall looks considerably better, @albertinisg could you respond to comments and fix suggestions you consider and then ask for a new review?

thanks

File: server/utils.js (hunk 1 above)
Comment (albertinisg) [inline server/utils.js]: True, my bad

File: server/utils.js (hunk 2 above)
Comment (albertinisg) [inline server/utils.js]: Agree, the check is already at authRequest function, so I'll remove it from here

File: server/utils.js (hunk 4 above)
Comment (albertinisg) [inline server/utils.js]: Yes, changing it!

File: server/utils.js (hunk 6 above)
Comment (albertinisg) [inline server/utils.js]: Not really misleading, but what it does is, replace the address with the one received from the geocoder. As the addresses are not really well formatted and using upperCase in the json from openEuskadi, I decided to made this kind of 'enrichment'. Regarding the `keyValues` option, this function is called to add Restaurants into Orion, so we need to add them using the `value` field as agreed.
Still, if you think it is not worth it, I can remove it and keep the address as they are

File: server/utils.js (hunk 7 above)
Comment (albertinisg) [inline server/utils.js:590]: Exactly, this is something I have planned for the next refactorization (all the methods from `orion.js` file)

**Comment by albertinisg** [comment]
Changes regarding the review process done in 023e29da79807ddac37e056256bea015d4c99db8. @jmcanterafonseca could you have a look? Thanks!

File: server/auth/authrequest.js [hunk 8]
```diff
@@ -54,9 +54,12 @@ function performRequest(endpoint, method, data, fiwareHeaders) {
       resolveWithFullResponse: true,
       json: true // Automatically stringifies the body to JSON
     };
+    if (querystring) {
```
Comment (jmcanterafonseca) [inline server/auth/authrequest.js]: code is duplicated below

File: server/utils.js (hunk 6 above)
Comment (jmcanterafonseca) [inline server/utils.js]: then fix is not a proper name, wouldn't it be completeAddress, nonetheless, please add comments they are always helpful

**Comment by albertinisg** [comment]
@jmcanterafonseca, removed duplicated code in 3bea80e70605262c0b189adbf86e2067bc78619c and renamed function in 7e693041e46693085aabf6dfc85615273dfd26e3

File: server/feeders/restaurantfeeder.js [hunk 9]
```diff
@@ -132,43 +133,54 @@ var feedOrionRestaurants = function() {
...
-
-    Object.keys(restaurantsData[pos]).forEach(function(element) {
+    Object.keys(restaurantsData[index]).forEach(function(element) {
 
-      var val = restaurantsData[pos][element];
+      var val = restaurantsData[index][element];
 
       if (element in addressDictionary) {
 
         if (val !== 'undefined' && val !== '') {
```
Comment (jmcanterafonseca) [inline server/feeders/restaurantfeeder.js]: if (val) suffices 

it checks for both conditions at the same time

File: server/feeders/restaurantfeeder.js [hunk 10]
```diff
@@ -38,12 +38,12 @@ var fiwareHeaders = {
 };
 
 var getAddress = function(restaurant) {
-  var address = restaurant.address.streetAddress + ' ';
-  if (restaurant.address.addressLocality) {
-    address += restaurant.address.addressLocality + ' ';
+  var address = restaurant.address.value.streetAddress + ' ';
+  if (restaurant.address.value.addressLocality) {
```
Comment (jmcanterafonseca) [inline server/feeders/restaurantfeeder.js:42]: I'm wondering why this trailing space is needed here??

File: server/utils.js [hunk 11]
```diff
@@ -463,53 +464,60 @@ function dataToSchema(listOfElements) {
   return newListOfElements;
 }
 
-function fixAddress(schemaObject, geoObject) {
+function completeAddress(schemaObject, geoObject) {
+  // The returned object will be POST/PATCH(ed),
```
Comment (jmcanterafonseca) [inline server/utils.js]: nit: add the comment outside the function body and using /\* */

File: server/utils.js [hunk 12]
```diff
@@ -752,14 +758,26 @@ function getTimeBetweenDates(from, to) {
...
       'type': 'PropertyValue',
-      'timestamp': date,
-      'name': 'occupancyLevels',
       'value': occupancyLevel
     }
   };
 }
 
+function generateId(name, date) {
+  if (date) {
```
Comment (jmcanterafonseca) [inline server/utils.js:779]: better if you create an intermediate variable, then you will save writing and make it clearer

File: server/feeders/restaurantfeeder.js (hunk 9 above)
Comment (albertinisg) [inline server/feeders/restaurantfeeder.js]: Done in ff19ca7a280ee02896dd99dbd986debf336f3426

File: server/feeders/restaurantfeeder.js (hunk 10 above)
Comment (albertinisg) [inline server/feeders/restaurantfeeder.js:42]: To format the address used in the geocoder

File: server/utils.js (hunk 11 above)
Comment (albertinisg) [inline server/utils.js]: Done in 24ebf0d3d65bd86f16690b17f4889dc6a932930b

File: server/utils.js (hunk 12 above)
Comment (albertinisg) [inline server/utils.js:779]: Done in 62a7ea877b8b08ea9cc3b045d99e6602fdbf0f17

**Comment by jmcanterafonseca** [comment]
LGTM
