### PR TITLE
Fix restaurant filter by date timestamp

### LINKED ISSUE #101: Restaurant filter by date returns wrong timestamp
As reported by @FiwareULPGC , the behavior when retrieving a restaurant by date is wrong. 

The example provided:

```
GET http://tourguide/api/orion/restaurant/Uriarte/date/2016-05-31T15:00:00.000Z

Response:
[
    {
        "@context": "http://schema.org",
        "@type": "Restaurant",
        "additionalProperty":
        [
            {
                "value": 80,
                "name": "capacity",
                "@type": "PropertyValue"
            },
            {
                "value": 0,
                "name": "occupancyLevels",
                "@type": "PropertyValue",
                "timestamp": "2016-05-12T07:02:27.852Z"
            }
        ],
   .........
```

### PR DESCRIPTION
**Pull request by albertinisg**
This PR fixes #101

### CODE REVIEW

File: server/utils.js [hunk 1]
```diff
@@ -800,11 +800,15 @@ function removeServicePath(headers) {
   return fiwareHeaders;
 }
 
-function returnResponse(data, res) {
+function returnResponse(data, res, date) {
   res.statusCode = data.statusCode;
   res.headers = data.headers;
   if (data.body) {
-    res.json(dataToSchema(data.body));
+    if (date) {
```
Comment (jmcanterafonseca) [inline server/utils.js]: this is really strange in JS. if date is an optional parameter then it should be handled by the dataToSchema function and not using the code you propose

Comment (albertinisg) [inline server/utils.js]: You are right. I've removed the unneeded check in e4617c4

**Comment by jmcanterafonseca** [comment]
LGTM, thanks
